/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpenHousesIndexRouteImport } from './routes/open-houses/index'
import { Route as OfficesIndexRouteImport } from './routes/offices/index'
import { Route as ListingsIndexRouteImport } from './routes/listings/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as OpenHousesOpenHouseKeyRouteImport } from './routes/open-houses/$openHouseKey'
import { Route as ListingsListingKeyRouteImport } from './routes/listings/$listingKey'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenHousesIndexRoute = OpenHousesIndexRouteImport.update({
  id: '/open-houses/',
  path: '/open-houses/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficesIndexRoute = OfficesIndexRouteImport.update({
  id: '/offices/',
  path: '/offices/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIndexRoute = ListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenHousesOpenHouseKeyRoute = OpenHousesOpenHouseKeyRouteImport.update({
  id: '/open-houses/$openHouseKey',
  path: '/open-houses/$openHouseKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsListingKeyRoute = ListingsListingKeyRouteImport.update({
  id: '/listings/$listingKey',
  path: '/listings/$listingKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/listings/$listingKey': typeof ListingsListingKeyRoute
  '/open-houses/$openHouseKey': typeof OpenHousesOpenHouseKeyRoute
  '/agents/': typeof AgentsIndexRoute
  '/listings/': typeof ListingsIndexRoute
  '/offices/': typeof OfficesIndexRoute
  '/open-houses/': typeof OpenHousesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/listings/$listingKey': typeof ListingsListingKeyRoute
  '/open-houses/$openHouseKey': typeof OpenHousesOpenHouseKeyRoute
  '/agents': typeof AgentsIndexRoute
  '/listings': typeof ListingsIndexRoute
  '/offices': typeof OfficesIndexRoute
  '/open-houses': typeof OpenHousesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/listings/$listingKey': typeof ListingsListingKeyRoute
  '/open-houses/$openHouseKey': typeof OpenHousesOpenHouseKeyRoute
  '/agents/': typeof AgentsIndexRoute
  '/listings/': typeof ListingsIndexRoute
  '/offices/': typeof OfficesIndexRoute
  '/open-houses/': typeof OpenHousesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/listings/$listingKey'
    | '/open-houses/$openHouseKey'
    | '/agents/'
    | '/listings/'
    | '/offices/'
    | '/open-houses/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/listings/$listingKey'
    | '/open-houses/$openHouseKey'
    | '/agents'
    | '/listings'
    | '/offices'
    | '/open-houses'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/mcp'
    | '/listings/$listingKey'
    | '/open-houses/$openHouseKey'
    | '/agents/'
    | '/listings/'
    | '/offices/'
    | '/open-houses/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  McpRoute: typeof McpRoute
  ListingsListingKeyRoute: typeof ListingsListingKeyRoute
  OpenHousesOpenHouseKeyRoute: typeof OpenHousesOpenHouseKeyRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  ListingsIndexRoute: typeof ListingsIndexRoute
  OfficesIndexRoute: typeof OfficesIndexRoute
  OpenHousesIndexRoute: typeof OpenHousesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-houses/': {
      id: '/open-houses/'
      path: '/open-houses'
      fullPath: '/open-houses/'
      preLoaderRoute: typeof OpenHousesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offices/': {
      id: '/offices/'
      path: '/offices'
      fullPath: '/offices/'
      preLoaderRoute: typeof OfficesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/': {
      id: '/listings/'
      path: '/listings'
      fullPath: '/listings/'
      preLoaderRoute: typeof ListingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-houses/$openHouseKey': {
      id: '/open-houses/$openHouseKey'
      path: '/open-houses/$openHouseKey'
      fullPath: '/open-houses/$openHouseKey'
      preLoaderRoute: typeof OpenHousesOpenHouseKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$listingKey': {
      id: '/listings/$listingKey'
      path: '/listings/$listingKey'
      fullPath: '/listings/$listingKey'
      preLoaderRoute: typeof ListingsListingKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  McpRoute: McpRoute,
  ListingsListingKeyRoute: ListingsListingKeyRoute,
  OpenHousesOpenHouseKeyRoute: OpenHousesOpenHouseKeyRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  ListingsIndexRoute: ListingsIndexRoute,
  OfficesIndexRoute: OfficesIndexRoute,
  OpenHousesIndexRoute: OpenHousesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
