/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as IndexOlderRouteImport } from './routes/index-older'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellersIndexRouteImport } from './routes/sellers/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as RentalsIndexRouteImport } from './routes/rentals/index'
import { Route as OpenHousesIndexRouteImport } from './routes/open-houses/index'
import { Route as OfficesIndexRouteImport } from './routes/offices/index'
import { Route as ListingsIndexRouteImport } from './routes/listings/index'
import { Route as InvestmentsIndexRouteImport } from './routes/investments/index'
import { Route as EstatesIndexRouteImport } from './routes/estates/index'
import { Route as BuyersIndexRouteImport } from './routes/buyers/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as SellersGetReadyRouteImport } from './routes/sellers/get-ready'
import { Route as SellersComparablesRouteImport } from './routes/sellers/comparables'
import { Route as SellersCalculatorRouteImport } from './routes/sellers/calculator'
import { Route as OpenHousesOpenHouseKeyRouteImport } from './routes/open-houses/$openHouseKey'
import { Route as ListingsListingKeyRouteImport } from './routes/listings/$listingKey'
import { Route as InvestmentsOpportunitiesRouteImport } from './routes/investments/opportunities'
import { Route as InvestmentsDueDiligenceRouteImport } from './routes/investments/due-diligence'
import { Route as InvestmentsCalculatorRouteImport } from './routes/investments/calculator'
import { Route as EstatesPropertiesRouteImport } from './routes/estates/properties'
import { Route as EstatesOrganizerRouteImport } from './routes/estates/organizer'
import { Route as EstatesCalculatorRouteImport } from './routes/estates/calculator'
import { Route as ApiUsageMetricsRouteImport } from './routes/api/usage-metrics'
import { Route as AgentsAgentKeyRouteImport } from './routes/agents/$agentKey'
import { Route as SearchGroupIndexRouteImport } from './routes/search/$group/index'
import { Route as RentalsGroupIndexRouteImport } from './routes/rentals/$group/index'
import { Route as SearchGroupValueRouteImport } from './routes/search/$group/$value'
import { Route as RentalsGroupValueRouteImport } from './routes/rentals/$group/$value'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexOlderRoute = IndexOlderRouteImport.update({
  id: '/index-older',
  path: '/index-older',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellersIndexRoute = SellersIndexRouteImport.update({
  id: '/sellers/',
  path: '/sellers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsIndexRoute = RentalsIndexRouteImport.update({
  id: '/rentals/',
  path: '/rentals/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenHousesIndexRoute = OpenHousesIndexRouteImport.update({
  id: '/open-houses/',
  path: '/open-houses/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficesIndexRoute = OfficesIndexRouteImport.update({
  id: '/offices/',
  path: '/offices/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIndexRoute = ListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsIndexRoute = InvestmentsIndexRouteImport.update({
  id: '/investments/',
  path: '/investments/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstatesIndexRoute = EstatesIndexRouteImport.update({
  id: '/estates/',
  path: '/estates/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyersIndexRoute = BuyersIndexRouteImport.update({
  id: '/buyers/',
  path: '/buyers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellersGetReadyRoute = SellersGetReadyRouteImport.update({
  id: '/sellers/get-ready',
  path: '/sellers/get-ready',
  getParentRoute: () => rootRouteImport,
} as any)
const SellersComparablesRoute = SellersComparablesRouteImport.update({
  id: '/sellers/comparables',
  path: '/sellers/comparables',
  getParentRoute: () => rootRouteImport,
} as any)
const SellersCalculatorRoute = SellersCalculatorRouteImport.update({
  id: '/sellers/calculator',
  path: '/sellers/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenHousesOpenHouseKeyRoute = OpenHousesOpenHouseKeyRouteImport.update({
  id: '/open-houses/$openHouseKey',
  path: '/open-houses/$openHouseKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsListingKeyRoute = ListingsListingKeyRouteImport.update({
  id: '/listings/$listingKey',
  path: '/listings/$listingKey',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsOpportunitiesRoute =
  InvestmentsOpportunitiesRouteImport.update({
    id: '/investments/opportunities',
    path: '/investments/opportunities',
    getParentRoute: () => rootRouteImport,
  } as any)
const InvestmentsDueDiligenceRoute = InvestmentsDueDiligenceRouteImport.update({
  id: '/investments/due-diligence',
  path: '/investments/due-diligence',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsCalculatorRoute = InvestmentsCalculatorRouteImport.update({
  id: '/investments/calculator',
  path: '/investments/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const EstatesPropertiesRoute = EstatesPropertiesRouteImport.update({
  id: '/estates/properties',
  path: '/estates/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const EstatesOrganizerRoute = EstatesOrganizerRouteImport.update({
  id: '/estates/organizer',
  path: '/estates/organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const EstatesCalculatorRoute = EstatesCalculatorRouteImport.update({
  id: '/estates/calculator',
  path: '/estates/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsageMetricsRoute = ApiUsageMetricsRouteImport.update({
  id: '/api/usage-metrics',
  path: '/api/usage-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentKeyRoute = AgentsAgentKeyRouteImport.update({
  id: '/agents/$agentKey',
  path: '/agents/$agentKey',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchGroupIndexRoute = SearchGroupIndexRouteImport.update({
  id: '/search/$group/',
  path: '/search/$group/',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsGroupIndexRoute = RentalsGroupIndexRouteImport.update({
  id: '/rentals/$group/',
  path: '/rentals/$group/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchGroupValueRoute = SearchGroupValueRouteImport.update({
  id: '/search/$group/$value',
  path: '/search/$group/$value',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsGroupValueRoute = RentalsGroupValueRouteImport.update({
  id: '/rentals/$group/$value',
  path: '/rentals/$group/$value',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/index-older': typeof IndexOlderRoute
  '/mcp': typeof McpRoute
  '/usage': typeof UsageRoute
  '/agents/$agentKey': typeof AgentsAgentKeyRoute
  '/api/usage-metrics': typeof ApiUsageMetricsRoute
  '/estates/calculator': typeof EstatesCalculatorRoute
  '/estates/organizer': typeof EstatesOrganizerRoute
  '/estates/properties': typeof EstatesPropertiesRoute
  '/investments/calculator': typeof InvestmentsCalculatorRoute
  '/investments/due-diligence': typeof InvestmentsDueDiligenceRoute
  '/investments/opportunities': typeof InvestmentsOpportunitiesRoute
  '/listings/$listingKey': typeof ListingsListingKeyRoute
  '/open-houses/$openHouseKey': typeof OpenHousesOpenHouseKeyRoute
  '/sellers/calculator': typeof SellersCalculatorRoute
  '/sellers/comparables': typeof SellersComparablesRoute
  '/sellers/get-ready': typeof SellersGetReadyRoute
  '/agents/': typeof AgentsIndexRoute
  '/buyers/': typeof BuyersIndexRoute
  '/estates/': typeof EstatesIndexRoute
  '/investments/': typeof InvestmentsIndexRoute
  '/listings/': typeof ListingsIndexRoute
  '/offices/': typeof OfficesIndexRoute
  '/open-houses/': typeof OpenHousesIndexRoute
  '/rentals/': typeof RentalsIndexRoute
  '/search/': typeof SearchIndexRoute
  '/sellers/': typeof SellersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/rentals/$group/$value': typeof RentalsGroupValueRoute
  '/search/$group/$value': typeof SearchGroupValueRoute
  '/rentals/$group/': typeof RentalsGroupIndexRoute
  '/search/$group/': typeof SearchGroupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/index-older': typeof IndexOlderRoute
  '/mcp': typeof McpRoute
  '/usage': typeof UsageRoute
  '/agents/$agentKey': typeof AgentsAgentKeyRoute
  '/api/usage-metrics': typeof ApiUsageMetricsRoute
  '/estates/calculator': typeof EstatesCalculatorRoute
  '/estates/organizer': typeof EstatesOrganizerRoute
  '/estates/properties': typeof EstatesPropertiesRoute
  '/investments/calculator': typeof InvestmentsCalculatorRoute
  '/investments/due-diligence': typeof InvestmentsDueDiligenceRoute
  '/investments/opportunities': typeof InvestmentsOpportunitiesRoute
  '/listings/$listingKey': typeof ListingsListingKeyRoute
  '/open-houses/$openHouseKey': typeof OpenHousesOpenHouseKeyRoute
  '/sellers/calculator': typeof SellersCalculatorRoute
  '/sellers/comparables': typeof SellersComparablesRoute
  '/sellers/get-ready': typeof SellersGetReadyRoute
  '/agents': typeof AgentsIndexRoute
  '/buyers': typeof BuyersIndexRoute
  '/estates': typeof EstatesIndexRoute
  '/investments': typeof InvestmentsIndexRoute
  '/listings': typeof ListingsIndexRoute
  '/offices': typeof OfficesIndexRoute
  '/open-houses': typeof OpenHousesIndexRoute
  '/rentals': typeof RentalsIndexRoute
  '/search': typeof SearchIndexRoute
  '/sellers': typeof SellersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/rentals/$group/$value': typeof RentalsGroupValueRoute
  '/search/$group/$value': typeof SearchGroupValueRoute
  '/rentals/$group': typeof RentalsGroupIndexRoute
  '/search/$group': typeof SearchGroupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/index-older': typeof IndexOlderRoute
  '/mcp': typeof McpRoute
  '/usage': typeof UsageRoute
  '/agents/$agentKey': typeof AgentsAgentKeyRoute
  '/api/usage-metrics': typeof ApiUsageMetricsRoute
  '/estates/calculator': typeof EstatesCalculatorRoute
  '/estates/organizer': typeof EstatesOrganizerRoute
  '/estates/properties': typeof EstatesPropertiesRoute
  '/investments/calculator': typeof InvestmentsCalculatorRoute
  '/investments/due-diligence': typeof InvestmentsDueDiligenceRoute
  '/investments/opportunities': typeof InvestmentsOpportunitiesRoute
  '/listings/$listingKey': typeof ListingsListingKeyRoute
  '/open-houses/$openHouseKey': typeof OpenHousesOpenHouseKeyRoute
  '/sellers/calculator': typeof SellersCalculatorRoute
  '/sellers/comparables': typeof SellersComparablesRoute
  '/sellers/get-ready': typeof SellersGetReadyRoute
  '/agents/': typeof AgentsIndexRoute
  '/buyers/': typeof BuyersIndexRoute
  '/estates/': typeof EstatesIndexRoute
  '/investments/': typeof InvestmentsIndexRoute
  '/listings/': typeof ListingsIndexRoute
  '/offices/': typeof OfficesIndexRoute
  '/open-houses/': typeof OpenHousesIndexRoute
  '/rentals/': typeof RentalsIndexRoute
  '/search/': typeof SearchIndexRoute
  '/sellers/': typeof SellersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/rentals/$group/$value': typeof RentalsGroupValueRoute
  '/search/$group/$value': typeof SearchGroupValueRoute
  '/rentals/$group/': typeof RentalsGroupIndexRoute
  '/search/$group/': typeof SearchGroupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/index-older'
    | '/mcp'
    | '/usage'
    | '/agents/$agentKey'
    | '/api/usage-metrics'
    | '/estates/calculator'
    | '/estates/organizer'
    | '/estates/properties'
    | '/investments/calculator'
    | '/investments/due-diligence'
    | '/investments/opportunities'
    | '/listings/$listingKey'
    | '/open-houses/$openHouseKey'
    | '/sellers/calculator'
    | '/sellers/comparables'
    | '/sellers/get-ready'
    | '/agents/'
    | '/buyers/'
    | '/estates/'
    | '/investments/'
    | '/listings/'
    | '/offices/'
    | '/open-houses/'
    | '/rentals/'
    | '/search/'
    | '/sellers/'
    | '/api/auth/$'
    | '/rentals/$group/$value'
    | '/search/$group/$value'
    | '/rentals/$group/'
    | '/search/$group/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/index-older'
    | '/mcp'
    | '/usage'
    | '/agents/$agentKey'
    | '/api/usage-metrics'
    | '/estates/calculator'
    | '/estates/organizer'
    | '/estates/properties'
    | '/investments/calculator'
    | '/investments/due-diligence'
    | '/investments/opportunities'
    | '/listings/$listingKey'
    | '/open-houses/$openHouseKey'
    | '/sellers/calculator'
    | '/sellers/comparables'
    | '/sellers/get-ready'
    | '/agents'
    | '/buyers'
    | '/estates'
    | '/investments'
    | '/listings'
    | '/offices'
    | '/open-houses'
    | '/rentals'
    | '/search'
    | '/sellers'
    | '/api/auth/$'
    | '/rentals/$group/$value'
    | '/search/$group/$value'
    | '/rentals/$group'
    | '/search/$group'
  id:
    | '__root__'
    | '/'
    | '/index-older'
    | '/mcp'
    | '/usage'
    | '/agents/$agentKey'
    | '/api/usage-metrics'
    | '/estates/calculator'
    | '/estates/organizer'
    | '/estates/properties'
    | '/investments/calculator'
    | '/investments/due-diligence'
    | '/investments/opportunities'
    | '/listings/$listingKey'
    | '/open-houses/$openHouseKey'
    | '/sellers/calculator'
    | '/sellers/comparables'
    | '/sellers/get-ready'
    | '/agents/'
    | '/buyers/'
    | '/estates/'
    | '/investments/'
    | '/listings/'
    | '/offices/'
    | '/open-houses/'
    | '/rentals/'
    | '/search/'
    | '/sellers/'
    | '/api/auth/$'
    | '/rentals/$group/$value'
    | '/search/$group/$value'
    | '/rentals/$group/'
    | '/search/$group/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IndexOlderRoute: typeof IndexOlderRoute
  McpRoute: typeof McpRoute
  UsageRoute: typeof UsageRoute
  AgentsAgentKeyRoute: typeof AgentsAgentKeyRoute
  ApiUsageMetricsRoute: typeof ApiUsageMetricsRoute
  EstatesCalculatorRoute: typeof EstatesCalculatorRoute
  EstatesOrganizerRoute: typeof EstatesOrganizerRoute
  EstatesPropertiesRoute: typeof EstatesPropertiesRoute
  InvestmentsCalculatorRoute: typeof InvestmentsCalculatorRoute
  InvestmentsDueDiligenceRoute: typeof InvestmentsDueDiligenceRoute
  InvestmentsOpportunitiesRoute: typeof InvestmentsOpportunitiesRoute
  ListingsListingKeyRoute: typeof ListingsListingKeyRoute
  OpenHousesOpenHouseKeyRoute: typeof OpenHousesOpenHouseKeyRoute
  SellersCalculatorRoute: typeof SellersCalculatorRoute
  SellersComparablesRoute: typeof SellersComparablesRoute
  SellersGetReadyRoute: typeof SellersGetReadyRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  BuyersIndexRoute: typeof BuyersIndexRoute
  EstatesIndexRoute: typeof EstatesIndexRoute
  InvestmentsIndexRoute: typeof InvestmentsIndexRoute
  ListingsIndexRoute: typeof ListingsIndexRoute
  OfficesIndexRoute: typeof OfficesIndexRoute
  OpenHousesIndexRoute: typeof OpenHousesIndexRoute
  RentalsIndexRoute: typeof RentalsIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  SellersIndexRoute: typeof SellersIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  RentalsGroupValueRoute: typeof RentalsGroupValueRoute
  SearchGroupValueRoute: typeof SearchGroupValueRoute
  RentalsGroupIndexRoute: typeof RentalsGroupIndexRoute
  SearchGroupIndexRoute: typeof SearchGroupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index-older': {
      id: '/index-older'
      path: '/index-older'
      fullPath: '/index-older'
      preLoaderRoute: typeof IndexOlderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sellers/': {
      id: '/sellers/'
      path: '/sellers'
      fullPath: '/sellers/'
      preLoaderRoute: typeof SellersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals/': {
      id: '/rentals/'
      path: '/rentals'
      fullPath: '/rentals/'
      preLoaderRoute: typeof RentalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-houses/': {
      id: '/open-houses/'
      path: '/open-houses'
      fullPath: '/open-houses/'
      preLoaderRoute: typeof OpenHousesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offices/': {
      id: '/offices/'
      path: '/offices'
      fullPath: '/offices/'
      preLoaderRoute: typeof OfficesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/': {
      id: '/listings/'
      path: '/listings'
      fullPath: '/listings/'
      preLoaderRoute: typeof ListingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments/': {
      id: '/investments/'
      path: '/investments'
      fullPath: '/investments/'
      preLoaderRoute: typeof InvestmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estates/': {
      id: '/estates/'
      path: '/estates'
      fullPath: '/estates/'
      preLoaderRoute: typeof EstatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyers/': {
      id: '/buyers/'
      path: '/buyers'
      fullPath: '/buyers/'
      preLoaderRoute: typeof BuyersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sellers/get-ready': {
      id: '/sellers/get-ready'
      path: '/sellers/get-ready'
      fullPath: '/sellers/get-ready'
      preLoaderRoute: typeof SellersGetReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sellers/comparables': {
      id: '/sellers/comparables'
      path: '/sellers/comparables'
      fullPath: '/sellers/comparables'
      preLoaderRoute: typeof SellersComparablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sellers/calculator': {
      id: '/sellers/calculator'
      path: '/sellers/calculator'
      fullPath: '/sellers/calculator'
      preLoaderRoute: typeof SellersCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-houses/$openHouseKey': {
      id: '/open-houses/$openHouseKey'
      path: '/open-houses/$openHouseKey'
      fullPath: '/open-houses/$openHouseKey'
      preLoaderRoute: typeof OpenHousesOpenHouseKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$listingKey': {
      id: '/listings/$listingKey'
      path: '/listings/$listingKey'
      fullPath: '/listings/$listingKey'
      preLoaderRoute: typeof ListingsListingKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments/opportunities': {
      id: '/investments/opportunities'
      path: '/investments/opportunities'
      fullPath: '/investments/opportunities'
      preLoaderRoute: typeof InvestmentsOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments/due-diligence': {
      id: '/investments/due-diligence'
      path: '/investments/due-diligence'
      fullPath: '/investments/due-diligence'
      preLoaderRoute: typeof InvestmentsDueDiligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments/calculator': {
      id: '/investments/calculator'
      path: '/investments/calculator'
      fullPath: '/investments/calculator'
      preLoaderRoute: typeof InvestmentsCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estates/properties': {
      id: '/estates/properties'
      path: '/estates/properties'
      fullPath: '/estates/properties'
      preLoaderRoute: typeof EstatesPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estates/organizer': {
      id: '/estates/organizer'
      path: '/estates/organizer'
      fullPath: '/estates/organizer'
      preLoaderRoute: typeof EstatesOrganizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estates/calculator': {
      id: '/estates/calculator'
      path: '/estates/calculator'
      fullPath: '/estates/calculator'
      preLoaderRoute: typeof EstatesCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/usage-metrics': {
      id: '/api/usage-metrics'
      path: '/api/usage-metrics'
      fullPath: '/api/usage-metrics'
      preLoaderRoute: typeof ApiUsageMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentKey': {
      id: '/agents/$agentKey'
      path: '/agents/$agentKey'
      fullPath: '/agents/$agentKey'
      preLoaderRoute: typeof AgentsAgentKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/$group/': {
      id: '/search/$group/'
      path: '/search/$group'
      fullPath: '/search/$group/'
      preLoaderRoute: typeof SearchGroupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals/$group/': {
      id: '/rentals/$group/'
      path: '/rentals/$group'
      fullPath: '/rentals/$group/'
      preLoaderRoute: typeof RentalsGroupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/$group/$value': {
      id: '/search/$group/$value'
      path: '/search/$group/$value'
      fullPath: '/search/$group/$value'
      preLoaderRoute: typeof SearchGroupValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals/$group/$value': {
      id: '/rentals/$group/$value'
      path: '/rentals/$group/$value'
      fullPath: '/rentals/$group/$value'
      preLoaderRoute: typeof RentalsGroupValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IndexOlderRoute: IndexOlderRoute,
  McpRoute: McpRoute,
  UsageRoute: UsageRoute,
  AgentsAgentKeyRoute: AgentsAgentKeyRoute,
  ApiUsageMetricsRoute: ApiUsageMetricsRoute,
  EstatesCalculatorRoute: EstatesCalculatorRoute,
  EstatesOrganizerRoute: EstatesOrganizerRoute,
  EstatesPropertiesRoute: EstatesPropertiesRoute,
  InvestmentsCalculatorRoute: InvestmentsCalculatorRoute,
  InvestmentsDueDiligenceRoute: InvestmentsDueDiligenceRoute,
  InvestmentsOpportunitiesRoute: InvestmentsOpportunitiesRoute,
  ListingsListingKeyRoute: ListingsListingKeyRoute,
  OpenHousesOpenHouseKeyRoute: OpenHousesOpenHouseKeyRoute,
  SellersCalculatorRoute: SellersCalculatorRoute,
  SellersComparablesRoute: SellersComparablesRoute,
  SellersGetReadyRoute: SellersGetReadyRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  BuyersIndexRoute: BuyersIndexRoute,
  EstatesIndexRoute: EstatesIndexRoute,
  InvestmentsIndexRoute: InvestmentsIndexRoute,
  ListingsIndexRoute: ListingsIndexRoute,
  OfficesIndexRoute: OfficesIndexRoute,
  OpenHousesIndexRoute: OpenHousesIndexRoute,
  RentalsIndexRoute: RentalsIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  SellersIndexRoute: SellersIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  RentalsGroupValueRoute: RentalsGroupValueRoute,
  SearchGroupValueRoute: SearchGroupValueRoute,
  RentalsGroupIndexRoute: RentalsGroupIndexRoute,
  SearchGroupIndexRoute: SearchGroupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
