export const routes = {
  google: {
    home: "/google",
    contact: "/google/contact",
    frequentlyAskedQuestions: "/google/frequently-asked-questions",
    paymentsSuccess: "/google/payments/success",
    policies: {
      Index: "/google/policies",
      AcceptableUse: "/google/policies/acceptable-use",
      Cookies: "/google/policies/cookies",
      Disclaimer: "/google/policies/disclaimer",
      Privacy: "/google/policies/privacy",
      Refunds: "/google/policies/refunds",
      TermsOfService: "/google/policies/terms-of-service",
      TrackingOptOut: "/google/policies/tracking-opt-out",
    },
    pricing: "/google/pricing",
    industry: {
      Index: "/google/industry",
      Plumbers: "/google/industry/plumbers",
      dentists: "/google/industry/dentists",
      towTrucks: "/google/industry/tow-trucks",
      locksmiths: "/google/industry/locksmiths",
      hvac: "/google/industry/hvac",
      electricians: "/google/industry/electricians",
      roofers: "/google/industry/roofers",
      pestControl: "/google/industry/pest-control",
      waterDamage: "/google/industry/water-damage",
      autoGlass: "/google/industry/auto-glass",
      garageDoor: "/google/industry/garage-door",
      treeService: "/google/industry/tree-service",
      applianceRepair: "/google/industry/appliance-repair",
      carpetCleaning: "/google/industry/carpet-cleaning",
      movers: "/google/industry/movers",
    },
    services: {
      Index: "/google/services",
      AdsAudit: "/google/services/ads-audit",
      GoogleMyBusiness: "/google/services/google-my-business",
      WeeklyStrategy: "/google/services/weekly-strategy",
      WeeklyStrategy4Weeks: "/google/services/weekly-strategy-4-weeks",
      WeeklyStrategy12Weeks: "/google/services/weekly-strategy-12-weeks",
      WeeklyStrategy48Weeks: "/google/services/weekly-strategy-48-weeks",
    },
    sitemapIndex: "/google/sitemap-index.xml",
  },
} as const
